/// Credits/Licenses page (SPEC.md section 5's copyright note: "ต้องมีหน้า
/// 'Credits/Licenses' ในแอปแสดงที่มาของคำแปล, related words และภาพ").
/// Attribution is read from the content build itself — `content_meta.licenses`
/// plus the distinct `source_license` values on the rows actually shipped — so
/// it stays accurate as the content pipeline's data changes instead of being
/// hardcoded here.
library;

import 'package:flutter/material.dart';

import 'package:vocab_app/data/vocab_store.dart';

class CreditsPage extends StatefulWidget {
  const CreditsPage({super.key, required this.store});

  final VocabStore store;

  @override
  State<CreditsPage> createState() => _CreditsPageState();
}

class _CreditsPageState extends State<CreditsPage> {
  Map<String, String> _meta = const {};
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final meta = await widget.store.loadContentMeta();
    if (!mounted) return;
    setState(() {
      _meta = meta;
      _loading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return Scaffold(
        appBar: AppBar(title: const Text('Credits / Licenses')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    // `content_meta.licenses` is a "; "-separated list written by the content
    // build, covering every source that fed the shipped rows.
    final translationSources = <String>{
      for (final entry in (_meta['licenses'] ?? '').split(';'))
        if (entry.trim().isNotEmpty) entry.trim(),
    };

    // No image pipeline ships yet; the section stays empty rather than
    // claiming attribution the build cannot back up.
    final imageSources = <String>{};

    // Sorted copies BEFORE the ternaries below. Inlining `x.toList()..sort()`
    // as a ternary branch is a trap: the cascade binds to the WHOLE
    // conditional (`(cond ? constList : list)..sort()`), so the empty case
    // sorted the const fallback list -> "Cannot modify an unmodifiable
    // list" crash (bug reported 2026-07-23).
    final sortedTranslations = translationSources.toList()..sort();
    final sortedImages = imageSources.toList()..sort();

    return Scaffold(
      appBar: AppBar(title: const Text('Credits / Licenses')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          _Section(
            title: 'Translations',
            items: sortedTranslations.isEmpty
                ? const ['No source data in this database']
                : sortedTranslations,
          ),
          const SizedBox(height: 16),
          const _Section(
            title: 'Related words',
            items: [
              'SWOW (Small World of Words, smallworldofwords.org) — CC BY-NC — '
                  'human free-association data, usable because this app is non-commercial',
              'Princeton WordNet — used to filter synonyms/antonyms (is_giveaway) and '
                  'categories (hypernym/category) for Odd One Out',
            ],
          ),
          const SizedBox(height: 16),
          _Section(
            title: 'Images',
            items: sortedImages.isEmpty
                ? const ['No images in this database yet (Openverse/Wikimedia, CC BY variants)']
                : sortedImages,
          ),
          const SizedBox(height: 16),
          const _Section(
            title: 'Example sentences',
            items: [
              'Generated by an LLM (see NOTES.md) — not copied from Oxford or any dictionary',
            ],
          ),
        ],
      ),
    );
  }
}

class _Section extends StatelessWidget {
  const _Section({required this.title, required this.items});

  final String title;
  final List<String> items;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title, style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 8),
            for (final item in items)
              Padding(
                padding: const EdgeInsets.only(bottom: 6),
                child: Text('• $item'),
              ),
          ],
        ),
      ),
    );
  }
}
