"""Re-rank freq_rank by SWOW-EN18 response frequency (user request
2026-07-24: "คำใช้บ่อย rerank ด้วย swow" — one ranking basis for the whole
word list instead of the A1 chunk keeping its curated Oxford-list order).

Reads responseStats.SWOW-EN.20180827.csv (Freq.R123 — how often the word
appears as a free-association response, the same metric extend_a2b1.py
Stage A used to pick/rank the A2/B1 words), then assigns fresh ranks:
band-major (all A1 < all A2 < all B1 — a learner still meets lower-band
words first), SWOW-frequency-descending inside each band; words with no
SWOW row sink to the end of their band, keeping their previous relative
order (stable sort).

Output: tools/swow_rerank.py with `RANKS = {headword: rank}`, consumed by
a merge shim at the end of wordlist.py. The shim remaps VALUES only — it
never reorders the WORDS list, so build_dataset.py's insert order (and
therefore every word id the app's srs_state rows reference) is unchanged.

Deterministic: rerunning produces byte-identical swow_rerank.py.
"""
import csv
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))

RESPONSE_STATS = Path(r"C:\Users\pimde\Downloads\SWOW-EN18") / \
    "responseStats.SWOW-EN.20180827.csv"

BAND_ORDER = {"A1": 0, "A2": 1, "B1": 2, "B2": 3}


def load_swow_freq():
    freq = {}
    with open(RESPONSE_STATS, encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames or []
        word_col = next((c for c in cols if c.lower() in ("response", "word")), cols[0])
        # Explicit column — the file's first unnamed column is a row index
        # that dwarfs the real counts (same gotcha as extend_a2b1 Stage A).
        freq_col = next((c for c in cols if c.lower() in ("freq.r123", "freq")),
                        None) or next(c for c in cols if "freq" in c.lower())
        for row in reader:
            w = (row.get(word_col) or "").strip().lower()
            if not w:
                continue
            try:
                n = float(row[freq_col])
            except (TypeError, ValueError):
                continue
            freq[w] = max(freq.get(w, 0), n)
    return freq


def main():
    from wordlist import WORDS  # ext merged; a previous rerank shim is a no-op for ranking below

    freq = load_swow_freq()

    # Stable sort: band-major, then SWOW freq desc, then previous rank
    # (keeps old relative order for ties / SWOW-missing words).
    entries = [(hw, pos, cefr, rank) for (hw, pos, cefr, rank) in WORDS]
    ordered = sorted(
        entries,
        key=lambda w: (BAND_ORDER.get(w[2], 9), -freq.get(w[0].lower(), 0.0), w[3]),
    )

    ranks = {hw: i + 1 for i, (hw, _pos, _cefr, _rank) in enumerate(ordered)}

    missing = [hw for (hw, _p, _c, _r) in entries if freq.get(hw.lower(), 0) == 0]
    print(f"{len(entries)} words re-ranked; {len(missing)} with no SWOW row "
          f"(sink to band end): {missing}")
    top = [hw for (hw, _p, c, _r) in ordered if c == "A1"][:15]
    print("A1 top-15 by SWOW:", top)

    out = TOOLS / "swow_rerank.py"
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write('"""Generated by rerank_swow.py — SWOW-EN18 Freq.R123 rank '
                'per headword (band-major). Do not edit by hand."""\n')
        f.write("RANKS = {\n")
        for hw, _pos, _cefr, _rank in ordered:
            f.write(f"    {hw!r}: {ranks[hw]},\n")
        f.write("}\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
